--[[
-- File name: intro.lua
-- Author: Fro-Q
-- Created: 2025-11-04 00:35:48
-- Last modified: 2025-11-04 14:44:10
-- ------
-- headup.nvim introduction and features
--]]

---
--- TOC ~
---@tag Headup.nvim
---@toc

--- Features ~
--- - Automatic Updates: Automatically updates metadata in file headers when saving
--- - Respects Manual Edits: Won't overwrite user manual changes to metadata
--- - Configurable: Support multiple file types with different patterns
---
--- Supported Content ~
--- - `current_time`: Current timestamp
--- - `file_size`: File size with automatic unit conversion (B, KB, MB, GB, TB)
--- - `line_count`: Number of lines in the file
--- - `file_name`: The base filename of the buffer
--- - `file_path`: File path relative to current working directory
--- - `file_path_abs`: Absolute file path
--- See |valid_contents| for more details.
---
--- Something to Note ~
--- - Headup.nvim only updates the first matched pattern in each file. If you
---   have multiple patterns in a single file, only the first one will be updated.
--- - 
---
--- Example Usage ~
---
---   A general one:
---@text >lua
---     require("headup").setup({
---       enabled = true,
---       silent = false,
---       time_format = "%Y-%m-%d %H:%M:%S",
---       max_lines = 20,
---       end_pattern = "\n",
---       exclude_pattern = "*/archive/*", -- skip archived notes
---       -- Update yaml front matter 'last_modified' in markdown files
---       {
---         -- pattern = {"*.md", "*.markdown"},
---         match_pattern = "last_modified:%s*(.-)%s*$",
---         content = "current_time",
---       },
---       -- Or a more general one:
---       {
---         pattern = "*",
---         match_pattern = "^%s*%-%-%s*[Ll]ast[%s_%-][Mm]odified:%s(.-)%s*$",
---         content = "current_time",
---       },
---     })
---
---@tag Headup.intro
---@toc_entry Introduction
